# Generated by Django 5.0.7 on 2024-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description_en_news_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
