# Generated by Django 5.0.7 on 2024-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
    ]
