# Generated by Django 5.0.7 on 2024-07-14 17:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_published_news_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
