# Generated by Django 5.0.7 on 2024-07-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
