# Generated by Django 5.0.7 on 2024-07-14 16:39

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, validators=[company.validators.validate_address])),
                ('phone_number', models.CharField(max_length=100, validators=[company.validators.validate_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('location', models.URLField(validators=[company.validators.validate_location])),
            ],
        ),
    ]
