# Generated by Django 5.0.7 on 2024-07-28 05:00

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, validators=[company.validators.validate_address])),
                ('phone_number', models.CharField(max_length=100, validators=[company.validators.validate_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('location', models.URLField(validators=[company.validators.validate_location])),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[company.validators.validate_phone_number])),
                ('massage', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact With Us',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_en', models.TextField(null=True)),
                ('question_uz', models.TextField(null=True)),
                ('question_ru', models.TextField(null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_uz', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(validators=[company.validators.validate_telegram_url])),
                ('facebook', models.URLField(validators=[company.validators.validate_facebook_url])),
                ('instagram', models.URLField(validators=[company.validators.validate_instagram_url])),
                ('lenkedin', models.URLField(validators=[company.validators.validate_linkedin_url])),
            ],
        ),
    ]
