# Generated by Django 5.0.7 on 2024-07-14 17:27

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(validators=[company.validators.validate_telegram_url])),
                ('facebook', models.URLField(validators=[company.validators.validate_facebook_url])),
                ('instagram', models.URLField(validators=[company.validators.validate_instagram_url])),
                ('lenkedin', models.URLField(validators=[company.validators.validate_linkedin_url])),
            ],
        ),
    ]
