# Generated by Django 5.0.7 on 2024-07-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contactwithus_rename_social_media_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={},
        ),
    ]
