# Generated by Django 5.0.7 on 2024-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(null=True),
        ),
    ]
