# Generated by Django 5.0.7 on 2024-07-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_questiontype_steptasktype_subjecttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clubmeeting',
            name='club',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.RemoveField(
            model_name='steptask',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='steptask',
            name='type',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='step_task',
        ),
        migrations.RemoveField(
            model_name='usertotaltestresult',
            name='step_test',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='stoplesson',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='subjecttitle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='test_question',
        ),
        migrations.RemoveField(
            model_name='usertestresult',
            name='test_answer',
        ),
        migrations.RemoveField(
            model_name='usertestresult',
            name='test_question',
        ),
        migrations.RemoveField(
            model_name='userclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='userclub',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertestresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertotaltestresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='clicked_count',
            new_name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lesson'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.lesson'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.student'),
        ),
        migrations.RenameModel(
            old_name='Club',
            new_name='Subtopic',
        ),
        migrations.AddField(
            model_name='unit',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subtopic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.unit'),
        ),
        migrations.DeleteModel(
            name='ClubMeeting',
        ),
        migrations.DeleteModel(
            name='StepTaskType',
        ),
        migrations.DeleteModel(
            name='StepTask',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='StopLesson',
        ),
        migrations.DeleteModel(
            name='SubjectTitle',
        ),
        migrations.DeleteModel(
            name='SubjectType',
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='UserClub',
        ),
        migrations.DeleteModel(
            name='UserSubject',
        ),
        migrations.DeleteModel(
            name='UserTestResult',
        ),
        migrations.DeleteModel(
            name='UserTotalTestResult',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
