# Generated by Django 5.0.7 on 2024-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_usertestresult_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttype',
            name='subject_type',
            field=models.CharField(choices=[('local', 'Local'), ('global', 'Global')], default='local', max_length=6),
        ),
    ]
